services:
  db:
    build: ./database/
    ports:
      - 5433:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - app-tier
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9000:9000
    volumes:
      - ./app/flask:/code
    networks:
      - app-tier
    command: /bin/bash -c "exec invoke run"
    env_file:
      - .env

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
