services:
  db:
    build: ./database/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres-test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9000:9000
    volumes:
      - ./app/flask:/code
    command: /bin/bash -c "python -u server.py & python -m unittest tests/test_models.py & coverage report -m --omit=tests/*"
    environment:
      - POSTGRES_DB=postgres-test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
