version: "3.8"
services:
  db:
    build: ./database/
    ports:
      - 5433:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - app-tier
    env_file:
      - .env
  app :
    build: ./app/
    depends_on:
      - db      
    ports:
      - 9000:9000
    volumes:
      - ./app/flask:/code
    networks:
      - app-tier   
    command: /bin/bash -c "exec invoke run"
    restart: on-failure
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge